- name: Copy Prometheus Config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart Prometheus Service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

