- name: Copy Record Rules
  ansible.builtin.template:
    src: rocord_rules.yml
    dest: /opt/prometheus/record_rules.yml

- name: Copy Prometheus Config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart Prometheus Service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Check Service is running
  ansible.builtin.shell: netstat -lntp | grep 9090


